SELECT TXN_ID , 
         ORIGIN_ACCOUNT_NUMBER , 
         RECIPIENT_DOCUMENT_NUMBER , 
         TYPE ,
         AMOUNT 
FROM TXNS 
EMIT CHANGES;

SELECT TXN_ID , 
         ORIGIN_ACCOUNT_NUMBER , 
         RECIPIENT_DOCUMENT_NUMBER , 
         TYPE ,
         AMOUNT 
FROM TXNS_TED 
EMIT CHANGES;


SELECT TXN_ID, 
         ORIGIN_ACCOUNT_NUMBER, 
         RECIPIENT_DOCUMENT_NUMBER, 
         AMOUNT, 
         SUSPECT_NAME  
FROM SUSPICIOUS_TXNS
EMIT CHANGES;