curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" \
      -H "Accept: application/vnd.kafka.v2+json" \
      --data '{"records": [
    {"value": {"class": "individual","person_id": "individual-1","individual": {"name": "Nome Cliente 1","cpf": "14897275903","email": "email_cliente_1_alterado@gmail.com","politically_exposed_person": true,"address": {"address_id": 11,"type": "Rua","zip_code": "00000011","street": "Rua 1 Alterada","number": "11","complement": "Casa Alterada","reference_point": "Supermercado Paulista","neighborhood": "Jardim Paulista","city": "Barueri","state": "São Paulo","country": "Brasil","primary": true},"phone": {"phone_id": 1,"type": "Celular","area_code": "11","country_code": "55","number": "911111111","primary": true},"person_id": "individual-1","status": "Aprovada"}}},
    {"value": {"class": "individual","person_id": "individual-2","individual": {"name": "Nome Cliente 2","cpf": "39079931870","email": "email_cliente_2_alterado@gmail.com","politically_exposed_person": true,"address": {"address_id": 22,"type": "Rua","zip_code": "00000022","street": "Rua 2 Alterada","number": "22","complement": "Casa Alterada","reference_point": "Supermercado Paulista","neighborhood": "Jardim Paulista","city": "Barueri","state": "São Paulo","country": "Brasil","primary": true},"phone": {"phone_id": 2,"type": "Celular","area_code": "22","country_code": "55","number": "922222222","primary": true},"person_id": "individual-2","status": "Aprovada"}}},
    {"value": {"class": "individual","person_id": "individual-1","individual": {"name": "Nome Cliente 1 - Alterado","cpf": "14897275903","email": "email_cliente_1_alterado@gmail.com","politically_exposed_person": true,"address": {"address_id": 11,"type": "Rua","zip_code": "00000011","street": "Rua 1 Alterada","number": "11","complement": "Casa Alterada","reference_point": "Supermercado Paulista","neighborhood": "Jardim Paulista","city": "Barueri","state": "São Paulo","country": "Brasil","primary": true},"phone": {"phone_id": 1,"type": "Celular","area_code": "11","country_code": "55","number": "911111111","primary": true},"person_id": "individual-1","status": "Aprovada"}}},
    {"value": {"class": "individual","person_id": "individual-2","individual": {"name": "Nome Cliente 2 - Alterado","cpf": "39079931870","email": "email_cliente_2_alterado@gmail.com","politically_exposed_person": true,"address": {"address_id": 22,"type": "Rua","zip_code": "00000022","street": "Rua 2 Alterada","number": "22","complement": "Casa Alterada","reference_point": "Supermercado Paulista","neighborhood": "Jardim Paulista","city": "Barueri","state": "São Paulo","country": "Brasil","primary": true},"phone": {"phone_id": 2,"type": "Celular","area_code": "22","country_code": "55","number": "922222222","primary": true},"person_id": "individual-2","status": "Aprovada"}}},
    {"value": {"class": "individual","person_id": "individual-1","individual": {"name": "Nome Cliente 1 - Alterado novamente","cpf": "14897275903","email": "email_cliente_1_alterado@gmail.com","politically_exposed_person": true,"address": {"address_id": 11,"type": "Rua","zip_code": "00000011","street": "Rua 1 Alterada","number": "11","complement": "Casa Alterada","reference_point": "Supermercado Paulista","neighborhood": "Jardim Paulista","city": "Barueri","state": "São Paulo","country": "Brasil","primary": true},"phone": {"phone_id": 1,"type": "Celular","area_code": "11","country_code": "55","number": "911111111","primary": true},"person_id": "individual-1","status": "Aprovada"}}},
    {"value": {"class": "individual","person_id": "individual-2","individual": {"name": "Nome Cliente 2 - Alterado novamente","cpf": "39079931870","email": "email_cliente_2_alterado@gmail.com","politically_exposed_person": true,"address": {"address_id": 22,"type": "Rua","zip_code": "00000022","street": "Rua 2 Alterada","number": "22","complement": "Casa Alterada","reference_point": "Supermercado Paulista","neighborhood": "Jardim Paulista","city": "Barueri","state": "São Paulo","country": "Brasil","primary": true},"phone": {"phone_id": 2,"type": "Celular","area_code": "22","country_code": "55","number": "922222222","primary": true},"person_id": "individual-2","status": "Aprovada"}}}
]}' "http://localhost:8082/topics/ev_person_individual"